name: 'sports_pipeline'
version: '1.0.0'

profile: 'sports_pipeline'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

models:
  sports_pipeline:
    staging:              # location of the sql 
      +materialized: view # does not need to be set, by default, dbt models are materialized as 'views'
    marts:
      +materialized: table
